---
- name: checking the database connection
  hosts: ops
  gather_facts: no
  vars: 
    ansible_ssh_user: root
  tasks: 
    - name: checking if admin can execute `sudo ovsdb-client dump` on the switch
      command: ovsdb-client dump
      become: yes
