---
- name: copy ssh public key to the switch
  hosts: ops
  vars: 
    ansible_ssh_user: root
    public_key: ~/.ssh/id_rsa.pub
  tasks:
    - authorized_key: user=root key="{{ lookup('file', public_key ) }}"
