---
- hosts: ops
  roles:
     - ops1

  vars:
    cli:
      host: 192.168.1.3
      port: 22
      username: netop
      password: netop

  tasks:
    - name: Run show commands
      ops_command:
        commands:
          - show version
          - show vlan
          - show vrf
          - show run
          - show ntp associations
        provider: "{{ cli }}"
      register: output
      connection: local

    - name: debug registered output
      debug: var=output
