# Based on the deprecated ansible docker image:
#
# https://hub.docker.com/r/ansible/ubuntu14.04-ansible/
#
# especially, this Dockerfile:
#
# https://github.com/ansible/ansible-docker-base/blob/master/devel-ubuntu14.04/Dockerfile
#
FROM ubuntu:14.04

MAINTAINER Kei Nohguchi <kei.nohguchi@hpe.com>

# Required package(s)
RUN apt-get -y update && \
    apt-get install -y openssh-client git \
                       python-yaml python-jinja2 python-httplib2 \
                       python-keyczar python-paramiko python-setuptools \
                       python-pkg-resources python-pip

# Prepare the ansible environment
RUN mkdir /etc/ansible
ADD inventory /etc/ansible/hosts
ADD ansible.cfg /etc/ansible/ansible.cfg

# Copy the ssh private key
RUN mkdir /root/.ssh
ADD .ssh/id_rsa /root/.ssh/id_rsa
RUN chmod 0700 /root/.ssh
RUN chmod 0400 /root/.ssh/id_rsa

# Get the latest ansible
RUN mkdir /opt/ansible
RUN git clone https://github.com/ansible/ansible.git \
        --recursive /opt/ansible/ansible
WORKDIR /opt/ansible/ansible
ENV PATH /opt/ansible/ansible/bin:/bin:/usr/bin:/sbin:/usr/sbin
ENV PYTHONPATH /opt/ansible/ansible/lib
ENV ANSIBLE_LIBRARY /opt/ansible/ansible/library
