---
ops_vrfs:
  - name: vrf_default
    ports: [1, 2, 3]
    bgp_routers:
      - as_number: 65000
        router_id: 172.16.0.1
        networks: [172.16.0.0/24, 172.16.1.0/24, 172.16.2.0/24]
        neighbors:
          - address: 172.16.1.2
            remote_as: 65001
          - address: 172.16.2.2
            remote_as: 65002

ops_ports:
  - name: 1
    ipv4_address: 172.16.0.1/24
  - name: 2
    ipv4_address: 172.16.1.1/24
  - name: 3
    ipv4_address: 172.16.2.1/24
  - name: 4
  - name: 5
  - name: 6
  - name: 7
  - name: 8
